INSERT INTO Materiales (nombre_material, descripcion, unidad_base, id_categoria, estado) VALUES
-- Materiales Eléctricos (35 registros)
('Cable THHN 2.5mm² negro', 'Conductor de cobre estañado 600V, aislamiento THHN', 'M', 5, 'Activo'),
('Interruptor termomagnético 20A 2P', 'Disyuntor bipolar 20A curva C', 'PZA', 5, 'Activo'),
('Canaleta metálica 40x40mm', 'Canaleta para instalaciones eléctricas, acero galvanizado', 'M', 5, 'Activo'),
('Tubo conduit PVC 20mm', 'Tubo rígido de PVC para instalaciones eléctricas', 'M', 5, 'Activo'),
('Portalámparas E27 porcelana', 'Portalámparas rosca Edison 27mm, material porcelana', 'PZA', 5, 'Activo'),
('Pulsador NO 22mm rojo', 'Pulsador normalmente abierto para panel 22mm', 'PZA', 5, 'Activo'),
('Contactor 25A 220V', 'Contactor magnético 3 polos 25A', 'PZA', 5, 'Activo'),
('Relé térmico 18-25A', 'Relé de sobrecarga ajustable para motor', 'PZA', 5, 'Activo'),
('Tablero eléctrico 12 módulos', 'Tablero plástico para instalación de módulos DIN', 'PZA', 5, 'Activo'),
('Base enchufe 2P+T 20A', 'Toma corriente industrial 20A con tierra', 'PZA', 5, 'Activo'),
('Breaker 16A 1P', 'Interruptor termomagnético unipolar 16A', 'PZA', 5, 'Activo'),
('Cable SY 5x2.5mm²', 'Cable blindado para instrumentación 5 conductores', 'M', 5, 'Activo'),
('Transformador 380/220V 5kVA', 'Transformador trifásico de aislamiento', 'PZA', 5, 'Activo'),
('Barrera de seguridad Ex i', 'Barrera intrínsecamente segura para áreas clasificadas', 'PZA', 5, 'Activo'),
('Fusible NH 160A', 'Portafusible NH con fusible 160A', 'PZA', 5, 'Activo'),
('Terminal ojalado 16mm²', 'Terminal de compresión para cable 16mm²', 'PZA', 5, 'Activo'),
('Conector MC4 par', 'Conector solar para paneles fotovoltaicos', 'PZA', 5, 'Activo'),
('Variador de frecuencia 5HP', 'Variador de velocidad para motor trifásico', 'PZA', 5, 'Activo'),
('Batería 12V 7Ah', 'Batería de gel para sistemas de respaldo', 'PZA', 5, 'Activo'),
('Sensor fotoeléctrico 10-30VDC', 'Sensor de barrera fotoeléctrica', 'PZA', 5, 'Activo'),
('Luminaria LED 50W IP65', 'Luminaria industrial estanca 50W', 'PZA', 5, 'Activo'),
('Cable UTP Cat6', 'Cable de red categoría 6', 'M', 5, 'Activo'),
('Tapa ciega para caja 4x2"', 'Tapa plástica para cajas de derivación', 'PZA', 5, 'Activo'),
('Interruptor crepuscular', 'Interruptor automático activado por luz ambiental', 'PZA', 5, 'Activo'),
('Regleta de terminales 12 polos', 'Regleta para conexión de conductores', 'PZA', 5, 'Activo'),
('Transformador corriente 100/5A', 'Transformador de corriente para medición', 'PZA', 5, 'Activo'),
('Contador energía activa', 'Medidor de energía eléctrica monofásico', 'PZA', 5, 'Activo'),
('Base enchufe USB 2.1A', 'Toma corriente con puertos USB integrados', 'PZA', 5, 'Activo'),
('Protector sobretensión 40kA', 'Descargador de sobretensiones para tableros', 'PZA', 5, 'Activo'),
('Candado seguridad 10mm', 'Candado para tableros eléctricos', 'PZA', 5, 'Activo'),
('Guía cables perforada', 'Guía metálica para organización de cables', 'M', 5, 'Activo'),
('Bandeja portacables 100mm', 'Bandeja metálica para tendido de cables', 'M', 5, 'Activo'),
('Cable flexible 3G1.5mm²', 'Cable para conexión de equipos móviles', 'M', 5, 'Activo'),
('Prensaestopa PG9', 'Prensaestopa metálico para entrada de cables', 'PZA', 5, 'Activo'),
('Caja derivación 8x8x6"', 'Caja estanca para empalmes eléctricos', 'PZA', 5, 'Inactivo'),

-- Instrumentación (25 registros)
('Transmisor presión 0-10bar', 'Transmisor de presión industrial 4-20mA', 'PZA', 6, 'Activo'),
('Indicador temperatura digital', 'Visualizador digital para termopar o RTD', 'PZA', 6, 'Activo'),
('Termopar tipo K 500mm', 'Sonda termopar tipo K con conector', 'PZA', 6, 'Activo'),
('Manómetro 0-25bar 4"', 'Manómetro de bourdon carátula 100mm', 'PZA', 6, 'Activo'),
('Switch nivel flotador', 'Interruptor de nivel por flotador', 'PZA', 6, 'Activo'),
('Caudalímetro turbina 1"', 'Medidor de caudal por turbina, salida pulso', 'PZA', 6, 'Activo'),
('Transmisor nivel radar', 'Sensor de nivel sin contacto tecnología radar', 'PZA', 6, 'Activo'),
('Analizador pH industrial', 'Sistema de medición de pH en línea', 'PZA', 6, 'Activo'),
('Célula carga 500kg', 'Célula de carga para básculas industriales', 'PZA', 6, 'Activo'),
('Presostato 0.5-10bar', 'Interruptor de presión ajustable', 'PZA', 6, 'Activo'),
('Termorresistencia PT100', 'Sonda RTD PT100 3 hilos', 'PZA', 6, 'Activo'),
('Convertidor señal I/P', 'Convertidor corriente neumática 4-20mA a 3-15psi', 'PZA', 6, 'Activo'),
('Panel indicador 96x96mm', 'Panel montaje frontal para instrumentos', 'PZA', 6, 'Activo'),
('Transmisor diferencial', 'Transmisor de presión diferencial', 'PZA', 6, 'Activo'),
('Válvula solenoide 1/2"', 'Válvula solenoide para instrumentación', 'PZA', 6, 'Activo'),
('Fuente alimentación 24VDC', 'Fuente regulada para instrumentos', 'PZA', 6, 'Activo'),
('Caja conexiones Ex d', 'Caja a prueba de explosión para instrumentos', 'PZA', 6, 'Activo'),
('Cable compensado 2x1.5mm²', 'Cable para termopares blindado', 'M', 6, 'Activo'),
('Conector M12 5 polos', 'Conector circular para sensores', 'PZA', 6, 'Activo'),
('Solenoide 24VDC', 'Actuador solenoide para válvulas', 'PZA', 6, 'Activo'),
('Convertidor USB-RS485', 'Interface conversión USB a RS485', 'PZA', 6, 'Activo'),
('Switch posición inductivo', 'Sensor inductivo de posición', 'PZA', 6, 'Activo'),
('Termómetro bimetálico 6"', 'Termómetro de varilla bimetálica', 'PZA', 6, 'Activo'),
('Registrador 4 canales', 'Registrador gráfico multiparámetro', 'PZA', 6, 'Activo'),
('Soporte montaje panel', 'Soporte para instalación en panel', 'PZA', 6, 'Inactivo'),

-- Cañería de conducción (20 registros)
('Tubo acero SCH40 1/2"', 'Tubería de acero al carbono sin costura', 'M', 2, 'Activo'),
('Tubería PVC presión 3"', 'Tubería de PVC para agua a presión', 'M', 2, 'Activo'),
('Tubo cobre tipo L 3/4"', 'Tubería de cobre para instalaciones sanitarias', 'M', 2, 'Activo'),
('Tubería HDPE PN10 4"', 'Tubería polietileno alta densidad', 'M', 2, 'Activo'),
('Tubo acero inox 316 2"', 'Tubería sanitaria de acero inoxidable', 'M', 2, 'Activo'),
('Tubería fibrocemento 6"', 'Tubería para conducción de agua', 'M', 2, 'Activo'),
('Tubo galvanizado 1"', 'Tubería roscable acero galvanizado', 'M', 2, 'Activo'),
('Tubería PP-R 20mm', 'Tubería polipropileno random para agua caliente', 'M', 2, 'Activo'),
('Tubo conduit EMT 3/4"', 'Tubería metálica para instalaciones eléctricas', 'M', 2, 'Activo'),
('Tubería CPVC 1/2"', 'Tubería clorada para agua caliente', 'M', 2, 'Activo'),
('Tubo multicapa 16mm', 'Tubería multicapa para instalaciones sanitarias', 'M', 2, 'Activo'),
('Tubería hierro dúctil 8"', 'Tubería para conducción de agua potable', 'M', 2, 'Activo'),
('Tubo acero SCH80 4"', 'Tubería de acero para alta presión', 'M', 2, 'Activo'),
('Tubería ABS 2"', 'Tubería para desagües', 'M', 2, 'Activo'),
('Tubo PEAD 110mm', 'Tubería para redes de gas', 'M', 2, 'Activo'),
('Tubería vidrio 50mm', 'Tubería de borosilicato para químicos', 'M', 2, 'Activo'),
('Tubo acero API 5L 6"', 'Tubería para conducción de hidrocarburos', 'M', 2, 'Activo'),
('Tubería PEX 3/4"', 'Tubería polietileno reticulado', 'M', 2, 'Activo'),
('Tubo acero al carbono 1.1/4"', 'Tubería para vapor baja presión', 'M', 2, 'Activo'),
('Tubería PE100 SDR11 2"', 'Tubería polietileno alta densidad', 'M', 2, 'Inactivo'),

-- Accesorios de cañería (20 registros)
('Codo 90° 1/2" SCH40', 'Codo soldable acero al carbono', 'PZA', 3, 'Activo'),
('Tee 1" x 1/2" roscada', 'Tee reductora hierro maleable', 'PZA', 3, 'Activo'),
('Unión universal 2"', 'Unión rápida para tuberías', 'PZA', 3, 'Activo'),
('Reducción concéntrica 3" a 2"', 'Reducción para cambio de diámetro', 'PZA', 3, 'Activo'),
('Cople roscado 3/4"', 'Conexión para unión de tuberías', 'PZA', 3, 'Activo'),
('Tapón macho 1/2"', 'Tapón para cierre de líneas', 'PZA', 3, 'Activo'),
('Niple 1" x 150mm', 'Niple de acero roscado', 'PZA', 3, 'Activo'),
('Brida deslizante 4" 150#', 'Brida para unión de tuberías', 'PZA', 3, 'Activo'),
('Codo 45° 2" SCH80', 'Codo para alta presión', 'PZA', 3, 'Activo'),
('Tapa ciega 6" 300#', 'Tapa para cierre de bridas', 'PZA', 3, 'Activo'),
('Unión dresser 1.1/2"', 'Unión flexible para reparaciones', 'PZA', 3, 'Activo'),
('Válvula check 1.1/4"', 'Válvula de retención tipo clapeta', 'PZA', 3, 'Activo'),
('Reducción excéntrica 8" a 6"', 'Reducción para líneas de succión', 'PZA', 3, 'Activo'),
('Cruce 3" x 2"', 'Conexión para derivaciones', 'PZA', 3, 'Activo'),
('Brida ciega 10"', 'Brida para aislamiento de líneas', 'PZA', 3, 'Activo'),
('Junta espiral 4"', 'Junta para bridas de acero inox', 'PZA', 3, 'Activo'),
('Tee soldable 3" SCH40', 'Tee de igual diámetro para soldar', 'PZA', 3, 'Activo'),
('Codo largo radio 6"', 'Codo para flujo con baja pérdida', 'PZA', 3, 'Activo'),
('Abrazadera reparación 2"', 'Abrazadera para reparación emergencia', 'PZA', 3, 'Activo'),
('Codo PVC 90° 3"', 'Codo para tuberías de PVC', 'PZA', 3, 'Inactivo'),

-- Tubos y perfiles (15 registros)
('Perfil UPN 80', 'Perfil estructural acero laminado', 'M', 4, 'Activo'),
('Tubo cuadrado 40x40x2mm', 'Tubo estructural de acero', 'M', 4, 'Activo'),
('Planchuela 1/4" x 4"', 'Planchuela de acero A36', 'M', 4, 'Activo'),
('Ángulo igual 2" x 1/4"', 'Ángulo estructural de acero', 'M', 4, 'Activo'),
('Tubo redondo 2" SCH40', 'Tubo de acero para uso mecánico', 'M', 4, 'Activo'),
('Perfil IPN 120', 'Viga I normal de acero', 'M', 4, 'Activo'),
('Fleje acero 50x3mm', 'Fleje de acero al carbono', 'M', 4, 'Activo'),
('Tubo rectangular 60x30x2mm', 'Tubo para estructuras metálicas', 'M', 4, 'Activo'),
('Barra redonda 20mm', 'Barra de acero mecanizable', 'M', 4, 'Activo'),
('Perfil T 50x50x5mm', 'Perfil T estructural', 'M', 4, 'Activo'),
('Planchuela galvanizada 3/16"x6"', 'Planchuela para exteriores', 'M', 4, 'Activo'),
('Tubo ovalado 30x15mm', 'Tubo para mobiliario industrial', 'M', 4, 'Activo'),
('Varilla roscada 12mm', 'Varilla para anclajes estructurales', 'M', 4, 'Activo'),
('Perfil HEA 100', 'Perfil H laminado en caliente', 'M', 4, 'Activo'),
('Tubo redondo inox 1.1/2"', 'Tubo de acero inoxidable', 'M', 4, 'Inactivo'),

-- Válvulas Industriales (15 registros)
('Válvula compuerta 2" 150#', 'Válvula de compuerta bridada', 'PZA', 1, 'Activo'),
('Válvula mariposa 6" lug', 'Válvula mariposa tipo wafer', 'PZA', 1, 'Activo'),
('Válvula globo 1.1/2" 300#', 'Válvula de globo para vapor', 'PZA', 1, 'Activo'),
('Válvula retención 3" swing', 'Válvula check tipo clapeta', 'PZA', 1, 'Activo'),
('Válvula bola 1" 600#', 'Válvula de bola full port', 'PZA', 1, 'Activo'),
('Válvula diafragma 1.1/2"', 'Válvula para fluidos corrosivos', 'PZA', 1, 'Activo'),
('Válvula aguja 1/2"', 'Válvula para regulación fina', 'PZA', 1, 'Activo'),
('Válvula seguridad 3/4" 10bar', 'Válvula de alivio de presión', 'PZA', 1, 'Activo'),
('Válvula piezoeléctrica 24VDC', 'Válvula actuada eléctricamente', 'PZA', 1, 'Activo'),
('Válvula neumática 3/2 vías', 'Válvula direccional neumática', 'PZA', 1, 'Activo'),
('Válvula esférica 4" 150#', 'Válvula esférica para gas', 'PZA', 1, 'Activo'),
('Válvula purga rápida 1/4"', 'Válvula para purga de aire', 'PZA', 1, 'Activo'),
('Válvula reguladora presión', 'Reguladora de presión aguas abajo', 'PZA', 1, 'Activo'),
('Válvula solenoide 3/4" AC', 'Válvula actuada eléctricamente', 'PZA', 1, 'Activo'),
('Válvula guillotina 8"', 'Válvula para sólidos en suspensión', 'PZA', 1, 'Inactivo'),

-- Lubricantes y Fluidos (10 registros)
('Aceite ISO 68', 'Aceite hidráulico anti-desgaste', 'LT', 7, 'Activo'),
('Grasa NLGI 2', 'Grasa multipropósito litio', 'KG', 7, 'Activo'),
('Fluido hidráulico HLP 46', 'Fluido para sistemas hidráulicos', 'LT', 7, 'Activo'),
('Aceite compresor 100', 'Aceite para compresores de tornillo', 'LT', 7, 'Activo'),
('Desengrasante industrial', 'Limpiador para maquinaria', 'LT', 7, 'Activo'),
('Aceite cadena SAE 80W', 'Aceite para cadenas de transmisión', 'LT', 7, 'Activo'),
('Refrigerante R134a', 'Gas refrigerante para sistemas HVAC', 'KG', 7, 'Activo'),
('Aceite turbina ISO 32', 'Aceite para turbinas de vapor', 'LT', 7, 'Activo'),
('Fluido corte soluble', 'Fluido para máquinas herramienta', 'LT', 7, 'Activo'),
('Grasa alimentaria NSF', 'Grasa para industria alimenticia', 'KG', 7, 'Inactivo'),

-- Químicos (10 registros)
('Ácido sulfúrico 98%', 'Ácido para baterías y procesos', 'LT', 8, 'Activo'),
('Hidróxido sodio 50%', 'Soda cáustica solución', 'KG', 8, 'Activo'),
('Inhibidor corrosión', 'Aditivo para protección metales', 'LT', 8, 'Activo'),
('Desincrustante calderas', 'Producto para limpieza de calderas', 'KG', 8, 'Activo'),
('Resina intercambio iónico', 'Resina catiónica para desmineralización', 'KG', 8, 'Activo'),
('Biocida no oxidante', 'Control de microorganismos en agua', 'LT', 8, 'Activo'),
('Antiespumante industrial', 'Control de espuma en procesos', 'LT', 8, 'Activo'),
('Detergente enzimático', 'Limpiador para industria alimentaria', 'LT', 8, 'Activo'),
('Desengrasante alcalino', 'Limpiador para talleres mecánicos', 'LT', 8, 'Activo'),
('Neutralizador pH', 'Regulador de pH para efluentes', 'KG', 8, 'Inactivo');